name: Build-System

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile
        run: |
          sudo apt-get install -y nasm gcc-multilib
          nasm -f elf32 boot.asm -o boot.o
          # Tüm C dosyalarını derle
          gcc -m32 -ffreestanding -O2 -Wall -Wextra -fno-pie -fno-stack-protector -c *.c
          # Hepsini kernel.bin'de birleştir
          ld -m elf_i386 -T linker.ld -o kernel.bin *.o
