name: Build WindOS

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: GCC 32-bit kur
        run: |
          sudo apt update
          sudo apt install -y gcc-multilib nasm

      - name: boot.asm derle
        run: |
          nasm -f elf32 boot.asm -o boot.o

      - name: lyn.c derle
        run: |
          gcc -m32 \
              -ffreestanding \
              -fno-pie \
              -fno-stack-protector \
              -nostdlib \
              -c lyn.c -o lyn.o

      - name: Kernel link
        run: |
          ld -m elf_i386 \
             -T linker.ld \
             -o windos.elf \
             boot.o lyn.o

      - name: Kernel kontrol
        run: |
          file windos.elf
